name: ai_gossip
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_markdown_latex: ^0.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Langar
      fonts:
        # Укажите путь к шрифту, если он используется
        - asset: fonts/Langar-Regular.ttf  # Предполагаем наличие шрифта

# Uncomment the assets section if you have images or other assets to include
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg